#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'crypt_reboot'

executor = CryptReboot::Cli::ParamsParsingExecutor.new
result = executor.call(ARGV)
exit result.call
