#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/setup'
require 'crypt_reboot'

args = ARGV - ['--verbose']

config = CryptReboot::Config.instance
config.save_patch = args.first
config.verbose = ARGV.include?('--verbose')

kernel = '/boot/vmlinuz'
cmdline = `cat /proc/cmdline`.chop
initramfs = '/boot/initrd.img'

loader = CryptReboot::KexecPatchingLoader.new
loader.call(kernel, cmdline, initramfs)
